### ISSUE TITLE
[Bug] : 프로젝트 만들기가 동작하지 않습니다

### ISSUE THREAD

**Issue by doong-jo** [boostcamp-2020/Project11-A-Web-FE-Performance-Monitoring-SDK#40]
안녕하세요. 재밌는 프로젝트 하셨네요~

다만 배포된 url에서 해보려고했는데 잘 안되네요. 한번 확인해주세요 :)

### To Reproduce
프로젝트 만들기 - 입력 후 - 프로젝트 만들기 클릭 

### Expected behavior
프로젝트가 생성되야할 것 같은데, 현재 반응 없음

### Screenshots
500 에러 발생
![스크린샷 2020-12-20 오후 9 53 06](https://user-images.githubusercontent.com/22005861/102713792-f3de4c80-430d-11eb-8deb-bc076d6ab7ce.png)

**Comment by minbert** [comment]
앗.. 저희가 놓쳤던 버그를 찾아주시고 제보해주셔서 정말 감사드립니다. 확인해보니 알림받을 메일 설정후 오류 감시 레벨을 설정 안했을 경우 해당 이슈가 발생하는 것 같습니다. 서버와 프론트 코드 확인 후 빠르게 고치도록 하겠습니다.

**Comment by maong0927** [comment]
고쳤습니다. ㅎㅎ 제보해주셔서 감사합니다 !!
